Repository 1000DownLoad/ProjectD, pull requests merged in 2023-12, with the labels that each got.

#1 📝 Write Initial Docs
  Wiki/README.md
  Wiki/commit_rules.md
Labels: 📝 Documentation

#7 Unused Remove File
  Client/Assets/Scripts/Systems/FlexReader/FlexReader 2.0.1.unitypackage.meta
  Client/Assets/Scripts/Systems/FlexReader/demo.unitypackage.meta
  Client/Assets/Scripts/Systems/FlexReader/i18n.unitypackage.meta
  Client/Assets/Util/GUI PRO Kit/ResourcesData/Sprite/Component/Icon_ItemIcons(x2)/ItemIcons(x2).unitypackage.meta
  Client/Assets/Util/GUI PRO Kit/ResourcesData/Sprite/Component/Icon_PictoIcons(x2)/PictoIcons(x2).unitypackage.meta
  Client/Assets/Util/GUI PRO Kit/ResourcesData/Sprite/Component/Icon_RuneIcons(x2)/RuneIcons(x2).unitypackage.meta
Labels: ♻️ Enhancement

#16 젠킨스 빌드 스크립트 추가. #1
  Client/Assets/Scripts/Editor.meta
  Client/Assets/Scripts/Editor/Build.meta
  Client/Assets/Scripts/Editor/Build/BuildScript.cs
  Client/Assets/Scripts/Editor/Build/BuildScript.cs.meta
Labels: ✨ Feature
